@ Only contains the text for the Mauville Man named Giddy. The rest is in scripts/mauville_man.inc
GiddyText_SoPretty::
	.string " fine AF!$"

GiddyText_SoDarling::
	.string " cute AF!$"

GiddyText_SoRelaxed::
	.string " chill AF!$"

GiddyText_SoSunny::
	.string " cool AF!$"

GiddyText_SoDesirable::
	.string " weird AF!$"

GiddyText_SoExciting::
	.string " happy AF!$"

GiddyText_SoAmusing::
	.string " funny AF!$"

GiddyText_SoMagical::
	.string " magical AF!$"

GiddyText_Is::
	.string " is$"

GiddyText_DontYouAgree::
	.string "\n"
	.string "You feel me, bro?$"

GiddyText_ISoWantToGoOnAVacation::
	.string "I so want to go on a vacation.\n"
	.string "Would you happen to know a nice place?$"

GiddyText_IBoughtCrayonsWith120Colors::
	.string "I bought crayons with 120 colors!\n"
	.string "Don't you think that's nice?$"

GiddyText_WouldntItBeNiceIfWeCouldFloat::
	.string "Wouldn't it be nice if we could float\n"
	.string "away on a cloud of bubbles?$"

GiddyText_WhenYouWriteOnASandyBeach::
	.string "When you write on a sandy beach,\n"
	.string "they wash away. It makes me sad.$"

GiddyText_WhatsTheBottomOfTheSeaLike::
	.string "What's the bottom of the sea like?\n"
	.string "Just once I would so love to go!$"

GiddyText_WhenYouSeeTheSettingSunDoesIt::
	.string "When you see the setting sun, does it\n"
	.string "make you want to go home?$"

GiddyText_LyingBackInTheGreenGrass::
	.string "Lying back in the green grass…\n"
	.string "Oh, it's so, so nice!$"

GiddyText_SecretBasesAreSoWonderful::
	.string "SECRET BASES are so wonderful!\n"
	.string "Can't you feel the excitement?$"
