	.align 2
gText_ConfirmSave::
	.string "Ayy bruh you tryna save?$"

gText_AlreadySavedFile::
	.string "Yalready did my dude.\n"
	.string "You tryna double save?$"

gText_SavingDontTurnOff::
	.string "SAVING…\n"
	.string "DON'T TURN OFF THE POWER.$"

gText_PlayerSavedGame::
	.string "{PLAYER} saved that shit.$"

gText_DifferentSaveFile::
	.string "WARNING!\p"
	.string "There is a different game file that\n"
	.string "is already saved.\p"
	.string "If you save now, the other file's\n"
	.string "adventure, including items and\l"
	.string "POKéMON, will be entirely lost.\p"
	.string "Are you sure you want to save now\n"
	.string "and overwrite the other save file?$"

gText_SaveError::
	.string "Save error.\p"
	.string "Please exchange the\n"
	.string "backup memory.$"

gText_SavingDontTurnOffPower::
	.string "SAVING…\n"
	.string "DON'T TURN OFF THE POWER.$"
